name: Release on semver tag

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-*"

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: fluid-pub/actions/.github/workflows/go-workload-release.yml@v1
    with:
      workload_kind: probe
      binary_name: proxmox-probe
      core_repository: fluid-pub/probe-core
      core_ref: develop
